### ISSUE TITLE
请问该项目如何在鸿蒙next系统上使用

### ISSUE THREAD

**Issue by HTwoOhwater** [Okysu/harmony-next-music-sharing#3]
作者的项目非常好，但是我不知道如何在我的设备上使用，请问有一些教程或方法吗？

**Comment by Okysu** [comment]
你可以下载DevEco Studio自己进行签名编译，使用开源项目[neteasecloudmusicapi](https://gitlab.com/Binaryify/neteasecloudmusicapi)，自己部署一个API或者使用本程序提供的默认的公共API服务器。

你也可以加Q群732815099，本应用进行邀请内测可以直接在尝鲜下载（需要先加入内测组）

**Comment by sunshe35** [comment]
没有release版本的吗？我想通过小白调试工具安装，自己不会编译。

**Comment by Okysu** [comment]
@sunshe35 
您可以加QQ群：732815099，我们会同步更新情况，并且提供默认的API服务器。
HAP可以访问：https://yby-zone.obs.cn-east-3.myhuaweicloud.com/music/app.hap
这个链接将永远指向最新的构建，同时并诚挚地建议您加入联系QQ群。

**Comment by sunshe35** [comment]
> @sunshe35 您可以加QQ群：732815099，我们会同步更新情况，并且提供默认的API服务器。 HAP可以访问：https://yby-zone.obs.cn-east-3.myhuaweicloud.com/music/app.hap 这个链接将永远指向最新的构建，同时并诚挚地建议您加入联系QQ群。

有考虑加入鸿蒙测试版上架商店吗？ 我看另一个app云音汇就加入了鸿蒙商店测试版，直接通过url就能更新了。

**Comment by Okysu** [comment]
> > @sunshe35 您可以加QQ群：732815099，我们会同步更新情况，并且提供默认的API服务器。 HAP可以访问：https://yby-zone.obs.cn-east-3.myhuaweicloud.com/music/app.hap 这个链接将永远指向最新的构建，同时并诚挚地建议您加入联系QQ群。
> 
> 有考虑加入鸿蒙测试版上架商店吗？ 我看另一个app云音汇就加入了鸿蒙商店测试版，直接通过url就能更新了。

@sunshe35  其实早就已经上过测试版了，一直处于满员状态，所以现在没办法通过邀请链接下载了，但是后续考虑直接上架。
